-- 1. Crear la base de datos
DROP DATABASE IF EXISTS "ResiduosToxicos";
CREATE DATABASE "ResiduosToxicos";
\c "ResiduosToxicos";

-- 2. REGION
CREATE TABLE REGION (
  RegCod   INTEGER       PRIMARY KEY,
  RegNom   VARCHAR(100)  NOT NULL
);

-- 3. CODIGO_RESIDUO
CREATE TABLE CODIGO_RESIDUO (
  CodResCod  VARCHAR(10)   PRIMARY KEY,
  CodResDesc VARCHAR(200)  NOT NULL
);

-- 4. EMPRESA_PRODUCTORA
CREATE TABLE EMPRESA_PRODUCTORA (
  EmpCod   SERIAL        PRIMARY KEY,
  EmpNom   VARCHAR(200)  NOT NULL,
  EmpRUC   VARCHAR(11)   NOT NULL,
  EmpDir   VARCHAR(250)  NOT NULL,
  EmpAct   VARCHAR(100),
  RegCod   INTEGER       NOT NULL REFERENCES REGION(RegCod)
);

-- 5. EMPRESA_TRANSPORTISTA
CREATE TABLE EMPRESA_TRANSPORTISTA (
  TrsEmpCod SERIAL        PRIMARY KEY,
  TrsNom    VARCHAR(200)  NOT NULL,
  TrsRUC    VARCHAR(11)   NOT NULL,
  TrsDir    VARCHAR(250)  NOT NULL,
  TrsCap    NUMERIC(8,2),
  RegCod    INTEGER       NOT NULL REFERENCES REGION(RegCod)
);

-- 6. DESTINO
CREATE TABLE DESTINO (
  DestCod     SERIAL         PRIMARY KEY,
  DestNom     VARCHAR(100)   NOT NULL,
  DestDir     VARCHAR(250)   NOT NULL,
  DestCap     NUMERIC(10,2),
  DestCapAct  NUMERIC(10,2),
  RegCod      INTEGER        NOT NULL REFERENCES REGION(RegCod)
);

-- 7. CONSTITUYENTE
CREATE TABLE CONSTITUYENTE (
  ConsCod  SERIAL         PRIMARY KEY,
  ConNom   VARCHAR(100)   NOT NULL,
  ConDes   VARCHAR(250),
  ConGrad  SMALLINT
);

-- 8. RESIDUO
CREATE TABLE RESIDUO (
  ResCod     SERIAL        PRIMARY KEY,
  ResNom     VARCHAR(100)  NOT NULL,
  ResDes     VARCHAR(250),
  CodResCod  VARCHAR(10)   NOT NULL REFERENCES CODIGO_RESIDUO(CodResCod),
  EmpCod     INTEGER       NOT NULL REFERENCES EMPRESA_PRODUCTORA(EmpCod)
);

-- 9. RESIDUO_CONSTITUYENTE
CREATE TABLE RESIDUO_CONSTITUYENTE (
  ResConsCod  SERIAL        PRIMARY KEY,
  ResCod      INTEGER       NOT NULL REFERENCES RESIDUO(ResCod),
  ConsCod     INTEGER       NOT NULL REFERENCES CONSTITUYENTE(ConsCod),
  ResConsPorc NUMERIC(5,2)
);

-- 10. TRASLADO_RESIDUO
CREATE TABLE TRASLADO_RESIDUO (
  TrasCod    SERIAL        PRIMARY KEY,
  TrasFec    DATE          NOT NULL,
  TrasCant   NUMERIC(8,2)  NOT NULL,
  TrasDsc    VARCHAR(250),
  ResCod     INTEGER       NOT NULL REFERENCES RESIDUO(ResCod),
  EmpCod     INTEGER       NOT NULL REFERENCES EMPRESA_PRODUCTORA(EmpCod),
  TrsEmpCod  INTEGER       NOT NULL REFERENCES EMPRESA_TRANSPORTISTA(TrsEmpCod),
  DestCod    INTEGER       NOT NULL REFERENCES DESTINO(DestCod)
);

